name: nuwecoin
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#  flutter pub run build_runner watch --delete-conflicting-outputs

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_collection: ^5.1.0
  flash: ^2.0.1

  flutter:
    sdk: flutter


  freezed_annotation: ^0.15.0
  json_annotation: ^4.3.0

  oxidized: ^4.2.0
  flutter_wall_layout: ^2.0.0
  flutter_redux: ^0.8.2
  redux_epics: ^0.15.0
  redux: ^5.0.0 

  retrofit: any
  logger: any
    
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.0.5
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

  freezed: ^0.15.0+1
  json_serializable: ^6.0.1
  lint: ^1.5.3
  retrofit_generator: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  
  uses-material-design: true

  fonts:
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
      
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: MontserratLight
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
      